# Generated by Django 4.1.5 on 2023-05-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesisapp', '0004_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('repliesUsername', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя пользователя для ответа')),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='likeComment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи лайкнувшие комментарий')),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='thesisapp.posts', verbose_name='Пост')),
                ('replies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to', to='thesisapp.comments')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='thesisapp.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коментарий к посту',
                'verbose_name_plural': 'Коментарии к постам',
                'ordering': ['-date'],
            },
        ),
    ]
