# Generated by Django 4.1.5 on 2023-05-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='creator',
        ),
    ]
