# Generated by Django 4.1.5 on 2023-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0009_alter_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ManyToManyField(related_name='received_messages', to='thesisapp.profile'),
        ),
    ]
