# Generated by Django 4.1.5 on 2023-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0010_chat_name_remove_chat_receiver_chat_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
