# Generated by Django 4.1.5 on 2023-06-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0011_chat_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='group',
            new_name='to_group',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('members', models.ManyToManyField(related_name='members', to='thesisapp.profile')),
                ('messages', models.ManyToManyField(related_name='messages', to='thesisapp.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='thesisapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='thesisapp.profile'),
        ),
    ]
