# Generated by Django 4.1.5 on 2023-06-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0012_rename_group_chat_to_group_remove_chat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unic_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='thesisapp.chat'),
        ),
    ]
